# -*- coding: utf-8 -*-
"""pypept_DRAVP, AVPdb, ADPDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFM8lIsw-mAUF-x3hn734hBQZegeBS06
"""

pip install git+https://github.com/Boehringer-Ingelheim/pyPept.git

# PyPept modules
from pyPept.sequence import Sequence
from pyPept.sequence import correct_pdb_atoms
from pyPept.molecule import Molecule
from pyPept.converter import Converter
from pyPept.conformer import Conformer
from pyPept.conformer import SecStructPredictor

# RDKit modules
from rdkit import Chem
from rdkit.Chem import Draw

def sec_to_smiles_biln(biln):
    # Crear secuencia
    seq = Sequence(biln)

    # Corregir átomos
    seq = correct_pdb_atoms(seq)

    # Crear molécula
    mol = Molecule(seq)
    romol = mol.get_molecule(fmt='ROMol')

    # Obtener SMILES
    smiles = Chem.MolToSmiles(romol)

    return smiles


resultado = sec_to_smiles_biln("A-A-C-T-A-C-T-M-K")
print(resultado)

def sec_to_smiles_helm(helm):
    b = Converter(helm=helm)
    biln = b.get_biln()
    seq = Sequence(biln)
    # Correct atom names in the sequence object
    seq = correct_pdb_atoms(seq)

    # Loop wit the included monomers
    mm_list = seq.s_monomers
    for i, monomer in enumerate(mm_list):
        mon = monomer['m_romol']

    mol = Molecule(seq)
    romol = mol.get_molecule(fmt='ROMol')
    smiles = Chem.MolToSmiles(romol)

    return smiles


resultado = sec_to_smiles_helm("PEPTIDE1{[ac].D.T.H.F.E.I.A.[am]}$$$$V2.0")
print(resultado)

def peptido_con_guion(peptido):
    return "-".join(peptido)

# Ejemplo de uso
resultado = peptido_con_guion("hola")
print(resultado)  # h-o-l-a

"""BASE DE DATOS DRAVP: TODAS LAS SECUENCIAS SON BILN"""

import pandas as pd
df = pd.read_excel("/content/sample_data/DRAVP_Data_processing.xlsx")
df['Adicion_guion'] = df['Sequence'].apply(peptido_con_guion)
df['SMILES'] = df['Adicion_guion'].apply(sec_to_smiles_biln)

df.to_excel("/content/sample_data/DRAVP_Data_Ready_to_merge.xlsx")

"""BASE DE DATOS AVPdb: TODAS LAS SECUENCIAS SON BILN"""

import pandas as pd
df = pd.read_excel("/content/sample_data/AVPdb_Data_processing.xlsx")
df['Adicion_guion'] = df['Sequence'].apply(peptido_con_guion)
df['SMILES'] = df['Adicion_guion'].apply(sec_to_smiles_biln)

df.to_excel("/content/sample_data/AVPdb_Data_Ready_to_merge.xlsx")

"""BASE DE DATOS ADPDB: TODAS LAS SECUENCIAS SON BILN"""

import pandas as pd
df = pd.read_excel("/content/sample_data/ADPDB_Data_processing.xlsx")
df['Adicion_guion'] = df['Sequence'].apply(peptido_con_guion)
df['SMILES'] = df['Adicion_guion'].apply(sec_to_smiles_biln)

df.to_excel("/content/sample_data/ADPDB_Data_Ready_to_merge.xlsx")